### ISSUE TITLE
[convert] Multiple edf files vs. multi-frame stack

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1127]
`silx convert *edf` will by default write a scan_0 group and merge all data into it. 

Maybe option `--create-root-group` should be set by default for multiple EDF files ?

Anyway, `silx convert *edf` will probably most often be used to create a multi-frame file. Should we try to detect cases when the edf files are a stack of images, and do a `cat *edf > multiframe.edf` prior to running convert? Or add an explicit `--edf-stack` option to do this?

**Comment by vasole** [comment]
My experience trying that command under windows is an error message even after solving #1118 

I would say that unless directives are provided indicating a merge, each file should correspond to an individual entry in the final file. Probably not what the user wants but it is sure to work.

That should be already the current implementation so that at least it does not crash.
We could offer to detect the pattern ROOT_SCANNUMBER_DETECTORNUMBER_INDEXNUMBER.edf  that should be easy to couple with any SPEC file provided the user requests for it (or a SPEC file is provided)

**Comment by vasole** [comment]
Let me pout it clear. **We have to** provide a tool able to take a set of EDF (or any other image acquisition format files) and associate them to a particular scan of a SPEC file. In other words, we have to be able to provide a merging tool. So, I am not asking for a lot of cases. Just two:

- The user has explicitely requested to take all input files as members of a stack. Therefore all the frames have to have the same shape.

- The user has followed the convention most widely accepted at the ESRF concerning the naming.

The simplest solution is of course to implement just the first one giving the **_possibility to specify the output path_** in the HDF5 file. That would allow to make the things simpler by taking a two steps approach. For instance, the SPEC file is converted and then the associated images are addded to a particular entry explicitely asking to be merged and under what path. A URI would do the job. So basically the option:

- The user has explicitely requested to take all input files as members of a stack. Therefore all the frames have to have the same shape.

Plus the possibility to specify -o outputfile.h5::/path/to/place would be enough.

The example below looks to me pretty obvious to understand:

silx convert --stack *.edf -o destination_file:::/entry_0/instrument/detector_x
