### ISSUE TITLE
[silx view] Also open .npz files

### ISSUE THREAD

**Issue by vincefn** [silx-kit/silx#1152]
npz files can be compressed and contain multiple arrays contrary to npy

**Comment by vallsv** [comment]
Hi,

There is 2 problems here:
- `fabio` do not support `npz`, and it would better to use it for `io`. But now we easily can deal with that since we have our new module `silx.io.commonh5`.
- Our `io` module was designed to expose Nexus compliant format. If you expect to store a multiframe-like data in an `npz`, there is no problem to expose it. But if you expect to store heterogeneous data, we have to decide if we want to expose this kind of format and how to do it.

**Comment by vincefn** [comment]
An npz file is essentially a dictionary of arrays, so similar to a flat hdf5 file. I was under the impression the npy file was seen as a virtual hdf5 file - I guess from the fabio interface, I have not looked at the actual code.
It would be interesting for heterogeneous data, there are a lot of npz files around as they are a lot simpler to generate than hdf5, so it would be very useful.

**Comment by t20100** [comment]
This could be done by adding a `npzh5` module which expose the structure of the .npz file as it is, right?

**Comment by vallsv** [comment]
Yes. That's a 3-liner if we just want to expose the content as it is.

**Comment by t20100** [comment]
I would expose the content as it is (we cannot infer or expect anything about the content).
To me it's like a HDF5 file not following any convention.
