### ISSUE TITLE
silx open takes very long for multiframe edf stacks

### ISSUE THREAD

**Issue by carichte** [silx-kit/silx#1168]
Dear all,

we have multiframe edf files with typically 516x516x20000 pixels.
To my experience, it takes very long to open these files simply with `silx.open` and using a small script based on `silx.third_party.EdfFile` is much faster. (also if I use it for conversion to h5)
Is it possible to use the third_party function to speed up silx.open and, this way, also silx view?
This would allow a fast inspection of scans during our measurements.

**Comment by vallsv** [comment]
Hi.

`silx.io.open` to open EDF was not designed to be efficient, but to be NeXus compatible. Then, if you need efficiency, don't use it. Or use it to convert first your data to an h5 file, it was designed for that.

We maybe can improve small things here and there, but i am quite sure using `EdfFile` will not change anything to the efficiency.

BTW, if you want to create your own h5 file, i recommend you to read your EDF files using `fabio`.

**Comment by carichte** [comment]
Ok, using EdfFile for opening such an edf file takes 50sec on our gpu machine.
In contrast, I interrupted fabio.open after it tried for several hours. (One CPU core loaded and moderate memory usage). 
Maybe that is the reason why also silx.open has this problem.

Furthermore, even though I can write my own script using EdfFile, it would be nice to be able to use the silx viewer.

**Comment by vallsv** [comment]
If you have efficiency problem with `fabio.open` vs `EdfFile` it can be nice to take a look. Is there a way to access to your data, and to be able to check that?

**Comment by t20100** [comment]
To me it is worth to be able to load data files (edf, tiff, npy, npz) in `silx view` as is without converting multi-frames to stack and creating an ESRF-nexus-like structure so that `silx view` would be as slow as the data format is (but not more).
We've started discussing this with @vallsv, the conversion to the ESRF-nexus structure could be available as a command-line option or as a protocol `hdf5://myfile.edf` or any other alternative.

**Comment by carichte** [comment]
Thanks,

there are many data examples. The one I tested is here:
/data/id01/inhouse/UPBLcomm/BLC10810/blc10810/id01/GaN_IHP2/KMAP_2017_09_18_184734/mpx
just pick any of the edf files

For the benchmarking, I added:
`%time im = EdfFile.EdfFile("kmap00001.edf.gz", fastedf=True)`
`%time a = np.stack((im.GetData(i) for i in xrange(im.NumImages)))`

where `EdfFile` is `silx.third_party.EdfFile`.
I'm not really sure about the implications of fastedf though.

fabio.open did not succeed after few hours, as mentioned before

**Comment by vasole** [comment]
- fastedf has no implications at all. It is ignored and kept for compatibility.

@t20100, @vallsv Fix the problem at the source (fabio) prior to think about dropping silx functionalities.

**Comment by t20100** [comment]
@sole I was not thinking about dropping silx functionalities but adding one: open image files as they are.

**Comment by vasole** [comment]
@t20100  In that case the default has to be the current behavior and not the other way around as proposed above. 

A word of caution, sooner or later you will need to have to be able to select what to plot against what and you will want that selection to be applied to several "entries". The more uniform the access to the data the better.

**Comment by kif** [comment]
This is related to https://github.com/silx-kit/fabio/issues/18
There is quick-fix: recompress your file so that there are no more 144000 gzipped blocks but only one: it heavily disturbs the python's gzip which is doing the loop at the Python level which takes ages.

zcat filename.gz |gzip -c > recompressed.gz

Re-writing helps really a lot !

**Comment by carichte** [comment]
Any idea why EdfFile does not suffer from the bug and if fabio could be optimized in this respect?

**Comment by kif** [comment]
The issue comes from concatenating 144000 gzip blocks and pretend it is a single gzip. The bug affects only such kind of files. Python used to handle this in a very poor way. 

FabIO measures the size of the file which causes the issue here. 
Shall we put much effort into EDF as optimizing it would probably slow down the migration to HDF5 !

**Comment by vallsv** [comment]
Removing `measure_size` looks to improve a lot the result on Python 2. Then i will try to patch FabIO in order to get ride of the use of the size of the decompressed buffer.

```
In [3]: filename = "../data/edf/id01_carsten_richter/kmap00001.edf.gz"

In [7]: %timeit ii = EdfFile(filename, fastedf=True); (ii.GetData(i) for i in range(ii.NumImages))
1 loop, best of 3: 22.5 s per loop

In [10]: %timeit ii = fabio.edfimage2.EdfImage(); ii.read(filename); (ii.getframe(i) for i in range(ii.nframes))
1 loop, best of 3: 22.8 s per loop
```

**Comment by vallsv** [comment]
It should not. At least we have something as fast as EdfFile.

**Comment by t20100** [comment]
OK let's close it, please reopen if needed
