### ISSUE TITLE
[ColorMapDialog] modal to non modal ?

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#1192]
I would personally prefer to have a NonModal ColormapDialog.
This way users can 'play with the different colormap' and other tool more easily from my point of view and just keep the dialog open somewhere.

**Comment by t20100** [comment]
That would be much better, but then you have to make sure the dialog and the plot remains consistent when the plot is updated.
This is not handled, and that's why the dialog is modal.
Now that there is a Colormap object and events in plot items, it should be much simpler to do. The burden might be if we need to keep the ColormapDialog API backward compatible, but it should not be directly used.
