### ISSUE TITLE
[plot3d] Tests fails on Windows

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1250]
Test `testNotFinite` fails on Windows with python2.7/pyqt4.11.4..
To investigate.

**Comment by PiRK** [comment]
For future reference, the TestCaseQt errors because of a remaining widget after the successful completion of the test. The widget refusing to disappear is a `QTreeView` that has a model set before the widget is shown. 
The widget has been removed from this particular `ScalarFieldWidget` test (in #1251) because it is not relevant to the test.
