### ISSUE TITLE
[plot] There is no getMarker API

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1826]
There is no way to reach a marker object. It would be good to expose `_getMarker` to the public API.

**Comment by vasole** [comment]
It is weird it is not reachable. Is it a good time to think about ``getItems(type="all")`` or a generic ``items`` API?

**Comment by t20100** [comment]
+1 for a generic API, i.e., moving `_getItem` and `_getItems` to the public API with a bit of rework.
Anyway, this is a recurrent need: PR #1723 also needs to get all histograms and scatter...

I would change `_getItems` signature to `getItems()` (i.e., remove the `withhidden` argument from `_getItems`). I'm also not sure the `kind` argument is useful as filtering can easily be done afterwards.
For the `getItem(legend, kind)` method, the `kind` argument is also not necessary if we decide to have unique legend across all kind of items.

In `plot3d` the API is: `add*` methods returning the created item for each kind of data (e.g., `add3DScatter`), `addItem`, `removeItem` and `clearItems` to manage the content and `getItems` to the content.

We can also consider changing `add*` functions to return objects instead of legends in the plot.

**Comment by vallsv** [comment]
I think, while there is a need of `kind`, it is not a good idea. I mean, this kind is useful internally, but should not be exposed. That is way a specific API for each kind is better, i think, whill we don't have strong unique IDs.

**Comment by vallsv** [comment]
I mean, if `getItems(id)` returns all the objects using legend=id (legend defined by the user), i think it is fine. But we should not expose `kind`, and we should not expose the internal ID of the objects.

**Comment by t20100** [comment]
Having a specific API for each kind of item makes the API grows with duplicated methods and increases the "cost" of adding a new kind of items.

**Comment by t20100** [comment]
closed by PR #2113 which adds `PlotWidget.getItems` method.
