### ISSUE TITLE
[silx view] Provide arcsinh as colormap

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2133]
This feature is available internally, but not yet provided to the GUI.

It could be useful to implement it for the next release.

Feedback from Peter ID16A.

**Comment by t20100** [comment]
There are quite a few things to change to fully integrate it (otherwise it would already be available... along with sqrt and pow):
- axes ticks and labels should support it in the ColorBar widget.
- OpenGL backend should support it (either implemented in shaders or with a fallback computing the colormapped image before sending it to the GPU (easier to maintain))
- plot3d is also using the Colormap object so it also needs to support it...

and I might have missed something.
So I don't think we can make it for next release... but I think we should add it soon (it's already been requested).
