### ISSUE TITLE
Random fail in CI on getSelectionMask

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#218]
It occurred many times since one week.

https://travis-ci.org/silx-kit/silx/jobs/156199005

```
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/silx/gui/plot/test/testMaskToolsWidget.py", line 169, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true
```

**Comment by t20100** [comment]
I've seen that.
It seems that on Travis with Xvfb (X virtual framebuffer), some extra wait are needed in the tests so that events are processed as opposed to Windows tests on appveyor where QApplication.instance().processEvents() is enough... I already added some to some tests.

To decide:
- Drop GUI tests on Linux on Travis because of those random fails: GUI already tested on Windows + Linux is the OS we almost all use during development
- Add QTest.qWait when something fails (Not really a satisfying solution)
- Add QTest.qWait call for each processEvents (but slows down tests...)
- Investigate further

**Comment by vasole** [comment]
There are simple options to test:

- while QApplication().hasPendingEvents() call to QApplication().processEvents() but perhaps there is a risk of endless loop. Perhaps a limit on the number of tries is needed.
- More than one call to QApplication().processEvents() ?

**Comment by t20100** [comment]
- I already tested calling processEvents twice.
- As for hasPendingEvents, we can try, but according to the doc, processEvents processes all pending events before returning... Yet I don't know if it processes new events emitted while it is called...
- QCoreApplication::flush might also worth trying.

The random nature of the issue is a problem to fix it...

**Comment by vallsv** [comment]
- Did you try processEvents(duration)?
- Do you think the issue is relative to a the `_drop` action?

**Comment by vasole** [comment]
@t20100 

In former Qt versions I recall processEvents having a timeout (of three seconds if not mistaken), So, more than one call could have an effect.

**Comment by t20100** [comment]
I could not reproduce the issue with Xfvb locally, it so far only occurs on Travis.

- In Qt 5.7, processEvents is said to process all pending events if no timeout is provided and hasPendingEvents is obsolete.
- Using flush or calling processEvents after each mouse also fails (at least sometimes)
- Adding qWait(20) after each event seems to work (so far)... This is actually what QTest is doing on OSX...
