### ISSUE TITLE
undecoded string fields from hdf5

### ISSUE THREAD

**Issue by kklmn** [silx-kit/silx#2449]
Hi,

When I get a string field by `silx_io.get_data(path-to-it)`, the returned value is actually of bytes type and needs decoding. This happens when I read from hdf5. And this is despite the Type is reported as string:
![image](https://user-images.githubusercontent.com/17322580/52797692-aee49180-3076-11e9-9460-58862a670187.png)

When I read from spec, the result is indeed str.
In my view, strings always should be decoded, so I consider it a bug (the hdf5 part, spec is fine).

**Comment by vasole** [comment]
In my opinion the "bug" is at the writer side: Sardana.

If not fixed by Sardana people, it will be automatically fixed by them when they will pass to Python 3. In terms of NeXus, both are accepted although it is preferred to have utf-8 strings.

With their current implementation, they are going to generate different output depending on the file being written under Python 2 or Python 3. What is in my opinion a bug at their side.

**Comment by vasole** [comment]
You will find a lot of literature at https://github.com/h5py/h5py/issues/379

**Comment by kklmn** [comment]
indeed, it is _a lot_ :)
You're probably right, this is on the Sardana side.
Thanks!

**Comment by vallsv** [comment]
I never try to use `get_data` to read strings. There is probably a conversion to do here for HDF5 field stored as ascii. But the field can then contain dirty sequence of bytes. And i don't know if it's a good idea to abstract h5py.

But i would prefer to read strings as strings, and not as an abstract sequence of bytes.
