### ISSUE TITLE
Precision when saving data to ASCII

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#25]
Question: How to handle precision by default in the ```save``` function when saving data to ASCII?

Does it need to be conservative and safe for all types (my opinion)?
Does it need to handle safely mixing types, e.g., for a curve x as int and y as float (also my opinion)?

Some examples:
- '%.7g' is safe for float32 but not float64 and int
- By default numpy.savetxt saves with '%.18e'. This is safe for float32 and float64, but not for int

  ```
  >>> numpy.savetxt('test.txt', (10000000000000001,))
  >>> numpy.loadtxt('test.txt')
  array(1e+16)
  ```

**Comment by PiRK** [comment]
If we want to be conservative we could try to detect the data type for each column when the user doesn't specify which format he wants. My suggestion would be:

- ``%d`` for integers
- ``%.7g`` for float32
- ``%.18e`` for float64

If the user specifies a format we should assume he knows what he is doing and not try to check types.

We can do something similar to numpy.savetxt (http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.savetxt.html): 
- ``fmt`` parameter: 

> single format (%10.5f), a sequence of formats, or a multi-format string, e.g. ‘Iteration %d – %10.5f’, in which case delimiter is ignored. 

Except we could set ``fmt=None`` as default and assign our default format depending on the type.

Should we handle complex values ?

But again, I would not have any moral problem if we just assumed that a vast majority users who don't bother defining a custom format would be happy with ``%.7g`` for all values, because it looks nicer and uses less disk space. We would just need to specify in the documentation that the default behavior is not safe for extremely large integers and very precise floats.

**Comment by t20100** [comment]
Yes, that's why I asked the question.
Do we want a conservative default behavior or a simple one?

**Comment by vasole** [comment]
Simple one. If it turns out to be not enough we change. A bit of Extreme Programming should make no harm. If we start from _"Cogito ergo sum"_ we are not going to get very far.
