### ISSUE TITLE
[fabioh5] Currently casting twice when converting from scalar to number

### ISSUE THREAD

**Issue by juliagarriga** [silx-kit/silx#2737]
In FabioReader class, when obtaining a value from the header in ``get_value``, the value is converted to a numpy object:
```
def _convert_scalar_value(self, value):
        """Convert a string into a numpy int or float.

        If it is not possible it returns a numpy string.
        """
        try:
            numpy_type = silx.utils.number.min_numerical_convertible_type(value)
            converted = numpy_type(value)
        except ValueError:
            converted = numpy.string_(value)
        return converted
```

But this dtype is later modified in ``__normalize_vector_type``. This value should not be casted twice, because it leads to a change of the original scalar value.

The next code is a summary of what is done to convert the type in fabioh5:
```
import numpy
from silx.utils.number import min_numerical_convertible_type

c = "-23.17"
_type = min_numerical_convertible_type(c)
converted = _type(c)
if numpy.issubdtype(_type, numpy.floating):
    result_type = numpy.result_type(_type, numpy.float32)
    second_conversion = numpy.array(converted, dtype=result_type)
    print(second_conversion)
```
Result is ``-23.171875`` because of how -23.17 is saved in numpy.float16.

**Comment by vallsv** [comment]
Did you try this patch then #2735?

**Comment by vallsv** [comment]
I don't think the problem is not about casting twice, but about the first type detection.

The second pass, is there to create an array (then the same type for all the elements), and this type is selected to be the same or one with more precision. Then you should not lose precision, and it avoid a second process to convert from string to binary type (it only deal from binary type to binary type).

**Comment by juliiaa28** [comment]
Yes, but what if the at the first pass the best precision is float16, and then when converted to float32. 
For example
```
>>> a = numpy.float16(2.1)
>>> a
2.1
>>> a.astype(numpy.float32)
2.0996094
```

**Comment by juliiaa28** [comment]
You still have this problem with all the values that are set as float16 in ``min_numerical_convertible_type``. If you try ``-23.1`` it returns numpy.float16, and then when the next function parses it to float32 you see the real loss of precision:`` -23.09375``. What I mean is, doing this first casting to float16 you are losing precision for nothing, because later you are casting it to float32 anyway, maybe it is better to cast it to float32 from the beginning (only when the flag is True).

**Comment by juliiaa28** [comment]
I created a different issue because for me the problem is not in the ``min_numerical_convertible_type`` function, but in the fabioh5 class. I think that when the flag of __at_least_32_bits is activated, the value shouldn't be casted to 16 bits and then again to 32. 

If I understood correctly, first the class changes all the values from a list to its min numerical type, and then it increases its type, if needed, so that all the values from the list have the same numerical type. What if first we check the type they should have, and then cast them all to this type? So they won't lose precision in this intermediate step. I.e, if the list of values is ["2.1", "3", "2.1555"], and the min numerical types are, respectively, [numpy.float16, numpy.uint8, numpy.float32]. Then instead of casting them all first to their respective types, we cast them all to float32 from the beginning, so no loss of precision is made in the intermediate step.

**Comment by vasole** [comment]
Yes, we agreed that when using HDF5 we would use float32 unless float64 was absolutely necessary. There should be no intermediate cast to float16.

**Comment by juliiaa28** [comment]
Yes but if they are casted to float64, because for one of the values in the array is necessary, they all too should be casted to it from the beginning, to not lose precision without reason:
```
>>> a = numpy.float32(0.1)
>>> b = numpy.float64(0.1)
>>> a + 0.2
0.30000000149011613
>>> b + 0.2
0.30000000000000004
>>> c = a.astype(numpy.float64)
>>> c + 0.2
0.30000000149011613
```

**Comment by vallsv** [comment]
`_convert_metadata_vector` contains all you need if you want to convert again from the strings. Remove the `converted` values, and use the string `values`. If you like i can update my patch with it.

**Comment by juliiaa28** [comment]
Yes I was looking at it right now, if instead of using the converted data we use the string and cast them at the end it should work fine.
