### ISSUE TITLE
[plot] Provide colormap API to reach color from data

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2862]
There is no obvious way to reach a color from few data from the `Colormap` object.

My main target is to display the color of a single picked data.

`applyToData` is only applied to the full data.

This method could take an optional min/max range.

- This should provide a consistent way with #2855 in order to reduce code overhead.
- And with #2739

**Comment by vallsv** [comment]
Here is my trick but it will not work for min/max based on statistics
```
value = 100
colormap = item.getColormap()
vmin, vmax = colormap.getColormapRange(item.getValueData(copy=False))
colors = colormap.applyToData(numpy.array([value, vmin, vmax]))
color = colors[0]
```

**Comment by t20100** [comment]
The `Colormap` objects have no connection with items and so with data.
It has the advantage of describing what is wanted rather than what is actually displayed... but this is also a limitation.

We need to think a bit on this. I see different options:
- keep some internal state (e.g., range or mean/std of last transformed dataset),
- add a new class that binds a colormap to some data,
- add a method in the item to get the color of one or many data elemets (in the end, it seems that it is what you need).

**Comment by vallsv** [comment]
I was thinking about passing the item or the min/max range as a param.
