### ISSUE TITLE
Mask improvement

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#292]
Here is some proposal after few time of observation on BM02, and own experience.

![mask-proposal](https://cloud.githubusercontent.com/assets/7579321/18867973/b6b7e23c-84a6-11e6-9fcc-3c82d4b25a30.png)
- A: This icons must display the current state of the diagram. At the same time, the behaviour of this icons are an action (you click on it to apply a new state). To fix this contradiction, and then to help the choice, i would be much better to provide a drop-down box: You see what you have, you click on what you want.
- B: This two icons looks very similar. For the mask, we can use a cartoonized "mask" (plus that's the style of most of our icons)
- C: 
  - To create a mask the mouse behaviour is not very convenient 
    - The zoom with mouse wheeel is quite slow
    - There is no way to pan the diagram when using a tool like polygon
    - Proposal: faster zoom + pan with middle mouse
    - Proposal: we should not use right mouse for tools (like polygons) if it is already used by the diagram for another thing (like context menu or zoom)
  - We don't see the border of the image. Is that possible to displayed it? Or to use another color background for the outside?
- D:
  - It would be much better to display the pen preview when we use it, like the polygon
  - Polygon preview (and rect) is displayed using black. Over a black image it is quite difficult to use. Would it be possible to test with a xor/negative filter?
  - It would be nice to have an ellipse
- E: It would be nice to change faster the size of the pen (with a slider for example)

While it is very important for pyFAI, i can fix most of it.

**Comment by t20100** [comment]
+1
- Changing the zoom speed of the wheel is very simple, other interaction changes need to change the interaction state machine.
- For the 2nd bullet of C, if what you want is to have the image not fully occupying the plotting area, in the plot API you can set some margins around the data (with setDataMargins) so that when you reset the zoom it adds a margin, otherwise you can control the limits of the axes.

**Comment by vallsv** [comment]
I talk about the border of the image. We dont really know where the image start.

![mask-image-border](https://cloud.githubusercontent.com/assets/7579321/18871913/05c80bac-84b8-11e6-9fef-ee7399c3d6e9.png)

**Comment by dnaudet** [comment]
Interesting.

Just my 2c for A and B :
I'm not too fond of having a menu to toggle between two exclusive (and mandatory, as in "one is always active") states. Instead of clicking once you have to click twice, it makes things a bit tedious. If we really want to display two separate actions I would rather have two checkable actions grouped in a QGroupAction (kinda like text alignment in most text editors).
I would consider using a menu when, for example, I need to choose between a set of exclusive tools or shapes that can then be turned on or off (mix a menu with a checkable action : a long press on the action drops the menu, a click on the action activates/deactivates the tool). Or when you have actions you select once and run repeatedly like "build", "build and run", "run tests" : you pick one in the menu, then click on the action to run it.

**Comment by vallsv** [comment]
That's also nice. And i have no idea what is better cause i don't know the users.
But i would prefer to not convert 2 icons on the tool bar into 4 for something which will not often used (1 time a session). Plus I already implement my proposal. Then i would say, at least it is an improvement.

**Comment by vallsv** [comment]
BTW here is the PR https://github.com/silx-kit/silx/pull/323

**Comment by vasole** [comment]
My opinion is that if one does not know what is better and there are already user interfaces applying one of the options, one should keep the option already implemented.

**Comment by vasole** [comment]
If your doubt is between a) the state + pull down menu and b) duplicating the number of icons, then I prefer a).

**Comment by vasole** [comment]
@vallsv @t20100  Is this ready to be closed?

**Comment by vallsv** [comment]
Yes. We can talk about mouse interaction into another issue.
Iv got another improvments now i know other features of the plot.
I close it
