### ISSUE TITLE
Changing NeXus entry naming from 1.1 to 1_1

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3139]
Initially raised by @vasole 

Apparently the currently used naming `1.1` does not pass NeXus validation tools.... So `1_1` should be used instead.
If it needs to be changed, the sooner the better.

Related discussion: https://github.com/nexusformat/definitions/issues/544

**Comment by jonwright** [comment]
You need a lowercase letter as first character : scan0001 like the image folders for example?

**Comment by vallsv** [comment]
It also must not start with a number if the validator is [a-zA-Z_][\w_]+

**Comment by vasole** [comment]
@jonwright 

No, we are going to keep starting by a number.

**Comment by vasole** [comment]
@vallsv 

We are going to keep starting groups by a number. We are not going to give up writing data treatments with a number indicating the order in which they took place because that presents things to the user in a way that is independent of the software used to inspect the files.

The BioXAS data treatment makes use of that.

**Comment by vasole** [comment]
@payno 

TomWer/NXtomomill will have to translate the sequence floating point scan values to the proper entry names. Probably it will have to handle both, the old and the new case.

**Comment by t20100** [comment]
It was decided NOT to change `1.1` to `1_1` or to strictly NeXus compliant naming (see https://manual.nexusformat.org/datarules.html#naming-conventions).
Anyway definitely not for release `0.13`.

Please reopen if more discussion is needed.
