### ISSUE TITLE
chuncked plotting / paginating large arrays

### ISSUE THREAD

**Issue by L0ric0** [silx-kit/silx#3154]
at the moment i am unable to view /plot a 5500x1000 array in silx, as the ram of the machine (16GB+) is running out. This could probably be solved, by only loading the part of the array, that is visible in the hdf5 view or chunking the data for plotting.

**Comment by t20100** [comment]
Even if `matplotlib` which is used by default by silx for the plot can consume quite a bit of memory, it should not be that bad...
Chunked access should not be needed for this kind of image size.

You can try to use the OpenGL rendering (requires pyopengl) which should use less memory:

- With silx view: `silx view --use-opengl-plot`
- From Python:
  - For all widgets:
    ```
    import silx
    silx.config.DEFAULT_PLOT_BACKEND = 'gl'   
    ```
  - For each widget:
    ```
    [...]
    from silx.gui.plot import PlotWidget
    w = PlotWidget(backend='gl')
    [...]
    ```

**Comment by vasole** [comment]
@t20100 

Time to offer the user to activate back modest image? We were able to visualize 10000x10000 images...

**Comment by vallsv** [comment]
That would also be nice for my use case. Big images with high-speed image rate with a fixed zoom could be faster to compute. For now i don't have feed back complains.

**Comment by t20100** [comment]
@vasole we are still able to display 10k*10k images, the way matplotlib is used now is very close to the principle used in modest image but without the display inaccuracy (at the cost a slightly more computation for first display since the colormap is applied once for all).

Anyway, displaying a 5 millions pixels image should not be an issue on a normal desktop. @L0ric0 can you provide more information (like operating system, version of silx, matplotlib, pyqt5 and the error you get)?

BTW, I started looking at progressive display of images, but for much bigger dataset than that. @vallsv if you are looking for performance, I would first give a change to the OpenGL backend.

**Comment by L0ric0** [comment]
@t20100 
|OS|silx|matplotlib|pyqt5|
|----|----|-------------|------|
|Debain Buster|0.9.0|3.0.2|5.11.3|
|Arch Linux|0.12.0|3.2.2|5.15.0|

I don't realy get an error just the OS running out of memory and freezing

I have attached a nexus file that exhibits the issue for the key `/excitations/laser0/electric_field` and `/excitations/laser0/intensity` but on a far lower scale (2GB ram) as github doesn't allow files over 10MB.
[mutm.zip](https://github.com/silx-kit/silx/files/4930342/mutm.zip)

A file which consumes more than 16GB for the stated keys can be found here:
https://uraziel.de/_matrix/media/r0/download/uraziel.de/df7bb18a2fb7357f1b1584a7d309c1700afdc635

**Comment by t20100** [comment]
The dataset `/excitations/laser0/electric_field/electric_field` is chunked with a chunk size of 1x1.
That's most probably the root of your issue (and reading is really slow), since I would not expect HDF5 and h5py to handle such a small chunk size in an efficient way.

Try to do this from Python, it will remove the chunking:
```
import h5py
f = h5py.File('20200714_153937_mutm.nxs', 'a')                                                              
ds = f['/excitations/laser0/electric_field/electric_field']
data = ds[()]
del f['/excitations/laser0/electric_field/electric_field']              
f['/excitations/laser0/electric_field/electric_field'] = data
f.close()
```

Memory usage is then reasonable and the image opens much faster (I was not patient enough to wait for the image to display with the original file).

**Comment by L0ric0** [comment]
@t20100 thank you for the tip, after writing with the right chunks its working pefektly
