### ISSUE TITLE
[Hdf5Item] Unecessary (?) data copy.

### ISSUE THREAD

**Issue by dnaudet** [silx-kit/silx#329]
I've been playing a bit with the model, it works great except when opening large datasets (possibly compressed datasets).

I think this is the culprit (in Hdf5Item::dataValue):

``` python
numpy_object = self.obj.value
```

DataSet.value returns a copy of the dataset (i.e : reads the whole dataset from the file). And since dataValue (with role=DisplayRole) can be called several times (at least twice, for each dataset displayed) when expanding an item, when the view is resized, or even when the view is destroyed (!)... each dataset gets decompressed several times.

Data should be loaded only if necessary : DataSet.shape should be used instead (doesn't load the dataset).

Also it looks like DataSet.value has been deprecated since h5py 2.1

**Comment by dnaudet** [comment]
Just putting it there as well since this is in the same method : 
```python
size = 1
for dim in numpy_object.shape:
    size = size * dim
```
(with numpy_object being a umpy array)

Doesn't size == numpy_object.size?

**Comment by vallsv** [comment]
- My tests was the loading of h5py classes (`group.get(...)`) was very slow. But i only test very small datasets (million dataset containing one int). Then thanks a lot for the feed back with big datasets. Plus i don't really know numpy nor h5py, then it is a very useful informations.
- Another thing is the sorting. h5py looks to return names sorted by alphabet instead of returning it by the structural order. Then to have the right order we have to sort again things.
- And the implemented sorting is right now very slow cause it do not use any cache and also tries to sort things using `start_time` and `end_time`
- The sorting is not enabled by default, but, if you use Qt5, it looks like it anyway sort items when you display it. There is a subtle change in the behaviour with Qt4. Then you also can have slow down here.

Ill try to improve that for the next release. Not it is too late.
