### ISSUE TITLE
Question about Fit action in Plot1D 

### ISSUE THREAD

**Issue by alexmarie78** [silx-kit/silx#3390]
Good evening.

I am trying to use a Plot1D widget, and I was wondering if it is possible to get the Fit dialog we get when clicking the corresponding action.
I would like to get the dialog in order to force using a ROI that would have been selected before using the Fit dialog. 

When I set a ROI on my Plot1D, whenever I select the curve and click the Fit action, the title of the dialog would still be the whole x axis instead of the ROI one. Is it possible to do so ?

I searched through the documentation but can't figure out how I could get the Fit dialog created by the action in the Plot1D widget, and I am sorry in advance if I missed something. ####

**Comment by t20100** [comment]
The widget opened by the fit action is `silx.gui.fit.FitWidget` (created here https://github.com/silx-kit/silx/blob/master/silx/gui/plot/actions/fit.py#L140).
And the doc of this widget is available here: http://www.silx.org/doc/silx/latest/modules/gui/fit/fitwidget.html#module-silx.gui.fit.FitWidget

I hope this can help.

**Comment by alexmarie78** [comment]
Good evening.
Thanks for your help ! 
By the way, I was already using the documentation to use the FitWidget. I now understand that I can get the new window (the one created by clicking on the action "Fit") by using getFitAction() function. I still don't know if it gives me the one instancied by the action or not.
Moreover, I don't understand how I can change data in the FitWidget when I already clicked "Fit" in Plot1D.

In fact, I am trying to force the FitWidget to use ROI when there is one defined. Thus, I am using the _setXRange() function of the FitWidget, and the function getFittedItem returns me a curve with the same size than the initial curve (the one without ROI limitations).

And I did not find any other function that could let me change the window title or the data to fit. I don't know if what I am doing is possible or not, this is why I posted this question here.

Again, thanks in advance for any response you can give me.

**Comment by t20100** [comment]
In `Plot1D`, the fit range is updated according to current limits of the X axis (see https://github.com/silx-kit/silx/blob/master/silx/gui/plot/PlotWindow.py#L854), this is an issue for what you want to achieve since zooming or panning will call `_setXRange`. You can disable this update with:
```python
plot1d.getFitAction().setXRangeUpdatedOnZoom(False)
```

The X range is also taken from the plot limits when the fit dialog is displayed, and as is there is no way to disable this and that's probably your issue.
It's those 2 lines:
https://github.com/silx-kit/silx/blob/master/silx/gui/plot/actions/fit.py#L155
https://github.com/silx-kit/silx/blob/master/silx/gui/plot/actions/fit.py#L192

A workaround could be to retrieve the `FitWidget` and install an [event filter](https://doc.qt.io/qt-5/eventsandfilters.html#event-filters) on it to set the X range when it becomes visible... but that's not really nice.
```python
fitwidget = plot1d.getFitAction()._getToolWindow()
```

`getFittedItem` returns the curve in the plot and don't care about `_setXRange`, so it is normal that it always returns the initial curve.

An option is also to write your own `FitAction` that manages the `FitWidget` as you want.

**Comment by alexmarie78** [comment]
Good morning.

Thanks for all your answers, this help a lot.
So this is not the right way to do it. I thought about something, is it possible to change how the "curve selection" works ? Because if I could change the selection of the curve, according to the ROI, then the data sent to the fit widget would be the reduced curve right ?

**Comment by t20100** [comment]
You can handle the curve selection with [`setActiveCurve`](https://github.com/silx-kit/silx/blob/master/silx/gui/plot/PlotWidget.py#L2186), but the curve as displayed in the plot will be selected will be the selected one.
I don't think it is a good idea to add a curve in the display of the plot to trick the fit action.

From what I understand from your problem, it seems rewriting your own fit action to start the `FitWidget` with appropriate information is one option. The other option would be to modify `FitAction` in order to have a mode where `_setXRange` is never called internally so you can set it externally.

**Comment by alexmarie78** [comment]
Hello again, it seems that rewriting my own ```FitAction``` to handle the start of the ```FitWidget``` was a good idea.
Thanks for your help.
I have one last concern about FitWidget and how it handles the theories. When I load one I made myself, it erases all of the theories we can use when intialising an empty ```FitWidget```. Is this the normal behavior ?

**Comment by t20100** [comment]
Good to hear you're finding your way through it!
