### ISSUE TITLE
Memory leak on opengl backend plots

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3443]
There is a lazy remove on the OpenGL backend in order to clean up OpenGL item in the right thread.

This code is executed during the `paintGL`.

If the plot is never displayed, items are never cleaned up.

But the plot can be updated with new items which will be never displayed.

As result the amount of items increase, until the plot is displayed again.

When using tabs, it's really common to have hidden plots.

----

With Flint, while the plot was on an hidden tab.

The plot is a curve plot with only 3 curves.

```
In [7]: len(w._silxPlot()._backend._glGarbageCollector)
Out[7]: 2190
```

After a display of this tab

```
In [8]: len(w._silxPlot()._backend._glGarbageCollector)
Out[8]: 0
```

----

A backport to 0.14 would be very welcome.

**Comment by vallsv** [comment]
Related to https://gitlab.esrf.fr/bliss/bliss/-/issues/2733

**Comment by tobiasvos** [comment]
We also encountered this issue and I can confirm that it is fixed from silx 0.14.1 onwards. However, on Debian 11 we are stuck on version 0.14.0. Is there a way to make the fix available on our operating system, without resorting to pip? For example by providing an official Debian backport, or an unofficial package for Debian 11 (right now these are only available for Debian 10)?

**Comment by t20100** [comment]
Hi,

To build unofficial Debian/Ubuntu packages, you can use this script: https://github.com/silx-kit/silx/blob/main/build-deb.sh
You can check the CI we use to build the unofficial packages we provide: https://gitlab.esrf.fr/silx/bob/main/-/blob/master/job-templates.yml#L810-865

Otherwise to get an official backport, since we are not much involved in official Debian packaging, it's best to ask a service company that provide this kind of service.

**Comment by tobiasvos** [comment]
Many thanks!

My apologies if this is in the wrong place, but I get the following error when trying to build a Debian package (and even with just `./build-deb.sh --help`):

```
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "/data/tobiasv/silx/src/silx/io/__init__.py", line 36, in <module>
  File "/data/tobiasv/silx/src/silx/io/utils.py", line 34, in <module>
  File "/usr/lib/python3.9/logging/__init__.py", line 26, in <module>
  File "/usr/lib/python3.9/traceback.py", line 5, in <module>
  File "/usr/lib/python3.9/linecache.py", line 11, in <module>
  File "/usr/lib/python3.9/tokenize.py", line 27, in <module>
ImportError: cannot import name 'open' from 'builtins' (unknown location)
```

The issue is that the silx/src/io subpackage shadows the standard library's io module. This issue can be circumvented by renaming src/silx/io to e.g. src/silx/_io, but then the build process still fails because `silx.io.xxx` is expected in many places.

Any clue how to get around this?

**Comment by t20100** [comment]
Hi,
I just opened a separate issue #3771 for this, let's continue the discussion there.
