### ISSUE TITLE
Issue with setLimits and keepAspectRation

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#3444]
In some cases I would like to define the plot area / limits before calling "Plot.addImage" (without resetting the zoom).

This work until we don't want to keep the aspect ration. When we ask to keep it then a part of the image is not displayed.

I tried to play with some `resetZoom`, `_setDirty`, use directly `Axis`...
The `PlotWidget.setLimits` function seems fine and the limits of the plot are not the same for the two backends.
But it looks like both are failing. Do you have any idea about the origin of it ?

Here is the simplest piece of code to reproduce it:
``` python
from silx.gui import qt
from silx.gui.plot import Plot2D
import numpy

app = qt.QApplication([])

# add plot widget 1
plot_widget_1 = Plot2D(backend="opengl")
plot_widget_1.setKeepDataAspectRatio(True)
plot_widget_1.setLimits(0, 216, 0, 216)
data = numpy.random.random(216*216).reshape(216, 216)
plot_widget_1.addImage(data, resetzoom=False)

plot_widget_1.show()
app.exec_()
```

image of the result:
with opengl
![image](https://user-images.githubusercontent.com/12907796/116433300-a89ef200-a849-11eb-86c3-71d8e11ec28b.png)

with matplotlib
![image](https://user-images.githubusercontent.com/12907796/116433396-bf454900-a849-11eb-9211-8ec2b627c566.png)

I tried to look a bit on it but the 'PlotWidget.setLimits' seems fine and this difference of limits between opengl and matplotlib are a bit strange.

**Comment by vallsv** [comment]
Limits are computed during the `repaint`.
I think thiere is some tricks on pyFAI to do such thing: https://github.com/silx-kit/pyFAI/blob/master/pyFAI/gui/helper/SynchronizeRawView.py
No idea if it is related.

**Comment by vallsv** [comment]
So probably you first have to display the plot so what the plot size is known, and then you can display the image.
In your case the `setLimits` is useless, the `resetZoom` should work well.

**Comment by t20100** [comment]
Until you display the widget the first time and get its actual size on screen, there is no way to know the exact limits when keep aspect ratio is on since the limits need to be adjusted.
Same, when you resize the widget, the limits are updated to keep the aspect ratio (i.e., it's a strong constraints).
And when you change the limits, you have to choose on which axis you keep the limits and on which you shrink/extend them... so what is done might not be suited for you.

There is different behaviours between the 2 backends because I though that was safer to let matplotlib handling the keep aspect ratio. But with a bit of care, it should be possible now to have `PlotWidget` taking care of it and having both backends not been concerned about that.

**Comment by payno** [comment]
Ok thank both of you for the details. In fact I think you already told me about it @t20100 or something very close.
So yes in my case I can get around by using a boolean and calling resetZoom when needed as mentioned by @vallsv
