### ISSUE TITLE
nexus_to_h5_dict function fails with Pint 0.20.1

### ISSUE THREAD

**Issue by mguijarr** [silx-kit/silx#3724]
Nexus writer uses `nexus_to_h5_dict` from `silx.io.dictdump`, but it fails with `AttributeError`:

```
Traceback (most recent call last):
   [...]
  File "/home/matias/miniconda3/envs/bliss_demo_env/lib/python3.9/site-packages/nexus_writer_service/io/nexus.py", line 712, in nxInit
    dicttonx(nxdict, h5group, update_mode="modify")
  File "/home/matias/miniconda3/envs/bliss_demo_env/lib/python3.9/site-packages/silx/io/dictdump.py", line 728, in dicttonx
    nxtreedict = nexus_to_h5_dict(
  File "/home/matias/miniconda3/envs/bliss_demo_env/lib/python3.9/site-packages/silx/io/dictdump.py", line 473, in nexus_to_h5_dict
    elif pint is not None and isinstance(value, pint.quantity.Quantity):
AttributeError: module 'pint' has no attribute 'quantity'
```

**Comment by t20100** [comment]
`pint.quantity` was removed in `pint` [v0.20](https://github.com/hgrecco/pint/releases/tag/0.20)

**Comment by mguijarr** [comment]
It seems there is no test in silx, with pint - and pint is not a silx dependency (from having a brief look at setup.py).

**Comment by t20100** [comment]
There is some tests, but they were skipped because `pint` was not installed on the CI.

https://github.com/silx-kit/silx/blob/a6e3b693e1f038839b05bf9080585363a85c2ee3/src/silx/io/test/test_dictdump.py#L528

Yes, `pint` is not in the dependencies of silx, it's only used so far is `isinstance(obj, pint.Quantity)` on what is provided by the user. But for me that could be added as a strong dependency to make things simpler.

PR #3725 fixes it.

**Comment by vallsv** [comment]
Or a test and a dependency with the tests only.

**Comment by t20100** [comment]
PR #3725 adds `pint` to `requirements.txt` and so to the CI test env so with this PR it will be tested.
