### ISSUE TITLE
compare: When composition mode is selected, the colormap from the scatter is selected

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3824]

**Comment by t20100** [comment]
That's because the control points are added with `addScatter` which makes the `scatter` "active" and so it is selected by the colormap dialog action.
If it was created as a `Scatter` and then added through `addItem`, it would not be automatically activated.

Then the ColormapDialog would no longer change this colormap, instead it would display the default colormap from the `PlotWidget` that should be the one used for data images.
