### ISSUE TITLE
[plot] color line

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#391]
When executing the following code the curve is displayed in dark instead of pink or whatever any color.
But the color setting will work for any other curve after the first one.
 
`p=Plot1D()`
`p.addCurve(x, y, color='pink', legend='sin', linewidth=6.0)`
`#p.addCurve(x, y, color='red', legend='sin')`
`p.show()`

**Comment by payno** [comment]
Not a bug, due to line selection

**Comment by t20100** [comment]
You can disable curve selection on the widget to avoid this.

**Comment by vasole** [comment]
As alternative, you can also decide which is your active curve color.

**Comment by t20100** [comment]
This is not the first time someone gets disturb by this highlight and think that the provided color is not taken into account.

A few propositions:
- Disable active curve handling by default. This makes the behavior backward compatible by just enabling the active curve handling when creating the widget and is very simple to implement.
- Do not highlight any curve until one is selected by the user or through the API.

**Comment by dnaudet** [comment]
Just for info, I was about to open the same issue yesterday! If we keep things this way maybe there should be at least an entry about it in the FAQ.

**Comment by dnaudet** [comment]
Argh. I just spent the last couple hours trying to figure out why my plot was all black even though I used a colormap. :rage1: :volcano:
An entry in the FAQ won't be enough. :laughing:

**Comment by vasole** [comment]
The problem is that the specialized widgets for 1D and 2D need to have "active" handling enabled by default because if not they do not know where to apply any of the functionalities: fit, ROI, profile, mask, ...

To disable it it by default can give more problems than just a "esthetic" problem. Probably @t20100 suggestion (Do not highlight any curve until one is selected by the user or through the API) is an appropriate compromise.

**Comment by dnaudet** [comment]
I agree!
Thanks.

**Comment by t20100** [comment]
Yes current behavior is miss-leading, the highlight only on user interaction would make it clear it is the highlight.

**Comment by vasole** [comment]
@PiRK 

- Fit action will have to prompt a message asking the user to select a curve if there are more than one curve in the plot and none is selected as active. If there is only one curve, it can take it even if it is not active.

- The 1D ROI widget should not complain (just fill the Raw and Net fields with question marks or something similar if there is no curve active)

**Comment by maurov** [comment]
Hello, my two cents comments on this:

- I also would like that the highlight would happen only when the user interact with the curve or if setted via the API, not by default.
- I find annoying and distracting that when the curve is highlighted the color changes to black. Instead of changing the color, I would propose that the highlighted curve simply gets a bigger linewidth.

**Comment by vasole** [comment]
If (and a big **IF** here) we go that way, I guess the active curve should offer more configuration options than just the color ... Reserving a color is the simplest solution.

For instance active color could set to None and line width could be expressed as an  integer factor to be applied to the line width to achieve highlight without change of color. However, line symbol has to be modified too (if the curve has no line it can be difficult to know it is the active curve).
