### ISSUE TITLE
[plot] stack API to be revised

### ISSUE THREAD

**Issue by srio** [silx-kit/silx#567]
1) Limits: the limits (for user values) should be defined in setStack for all axis dimensions (e.g., if stack(dim0,dim1,dim2) origin=(0,0,0)) 

2) Values: 
The user axes values should also be presented here (in addition to the position indices): 
![image](https://cloud.githubusercontent.com/assets/502315/22204757/f3833dae-e173-11e6-94ba-c0282918e34d.png)

**Comment by PiRK** [comment]
As discussed in #574, we decided that we need to come up with a better API for handling various schemes for axes  calibration. See https://support.hdfgroup.org/HDF5/doc/HL/H5DS_Spec.pdf, section 3.3 "What types of scales should be implemented?"
This will not be accomplished before release 0.4. 

Additionally, there are issues with the keyword `origin` that has a different meaning than in matplotlib (#421).

So we prefer to completely drop support for calibration for the coming release, rather than introducing an API and breaking it again in release 0.5.

**Comment by PiRK** [comment]
In the future, the plan is to replace the `origin` and `scale` keywords with a `calibration` object. One `calibration` per axis could be supported.
