### ISSUE TITLE
Specfile: Provide default generated code in a separate directory

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#65]
@PiRK 

With a python setup.py install, the generated specfile.c code is overwritten and git complains.

The default file should be provided in a default folder or under a different name and used if no cython is going to be used. See the setup.py of https://github.com/vasole/fisx to get an idea if necessary.

**Comment by PiRK** [comment]
I can see two simple solutions. 

The simplest, which solves only the problem of git complaining, is to put `specfile.c` in `.gitignore`. Whenever a change is made to  the `.pyx` file, one has to remember to do a `git add --force silx/io/specfile/specfile.c` after the file has been regenerated. This solution has the advantage of not adding any line of code to the `setup.py` and not changing the current behavior of `setup.py`.

The second solution is to also add the auto-generated file to `.gitignore`, then to make a copy of it to a file (for instance `specfile.c.in`) that will not be ignored, and to add code to the `setup.py` to copy `specfile.c.in` to `specfile.c` before compiling unless the command line `--force-cython` is specified when running `setup.py`. This adds a manual copy step and makes `setup.py` more complex. The `check_cython()` would have to be changed in the general `setup.py`: `--no-cython`, `fake_cythonize()` and `os.environ["WITH_CYTHON"] = "False"` should become the default behavior. 

This second option only makes sense if we don't trust Cython on the user computer to generate proper `.c` files.

**Comment by vasole** [comment]
The first solution still overwrites the supplied reference file.

The second solution serves to check if something was wrong at the 
building end with, for instance, a buggy cython or for speeding up things.

I am full for copying/renaming a supplied file and not just adding it to 
the list of ignored files.

**Comment by PiRK** [comment]
I worked on the issue, and found that if we want to go down that road, the required steps would be: 

- supply a default file, either in a different folder than the `pyx` file, or with a different name than the cython-generated file (e.g `silx/io/specfile.c.in`)
- add this file to `MANIFEST.in`
- in the local `silx/io/setup.py`, if `os.environ["WITH_CYTHON"]=="False"`, copy and rename the supplied file to wherever the compiler expects it to be (e.g `silx/io/specfile.c`)
- in the general `setup.py`, move `check_cython()` before `configuration()`, so that the environment variable `WITH_CYTHON` is set before importing the local `setup.py`
- optionally: remove the cython-generated C file from the repository (delete and add a line to `.gitignore`)

This solution seems to work on all tested platforms on my development branch https://github.com/PiRK/silx/tree/nocython

**Comment by vasole** [comment]
Ok, from the enhancement the only thing that is going to remain seems to be this:

- in the general setup.py, move check_cython() before configuration(), so that the environment variable WITH_CYTHON is set before importing the local setup.py

that I think it was already fixed by #73
