### ISSUE TITLE
[fitAction] Cycling colors

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#742]
The fact of showing the estimation introduces changes on the shown curves.

I see the interest, but I would not show the estimated curve unless explicitly requested. 

You should also keep in mind that if you do so, in addition you would have to handle the plot update if the user changes the estimation parameters by hand.

At this point (v 0.5.0) I would just get rid of the plot of the estimated curve.

**Comment by PiRK** [comment]
Note to myself:  keep #619 in mind

We cannot just do a new addCurve() with the same legend to replace the previous fit, because we said it is better to hide the display of the previous fit when the user restarts the same fit.
Maybe explicitly define the color. Or just hide the previous fit curve.

It is probably also a good idea to set a different line-style for fit curves compared to data curves.

**Comment by vasole** [comment]
Hiding seems like a simple (and therefore good) option.
