### ISSUE TITLE
[license] Could you please add a license file?

### ISSUE THREAD

**Issue by CJ-Wright** [silx-kit/silx#843]

**Comment by vasole** [comment]
Good catch!

**Comment by t20100** [comment]
In the mean time, the copyright file https://github.com/silx-kit/silx/blob/master/copyright describes the licenses on a per file basis.

**Comment by vasole** [comment]
We have to add a LICENSE file specifying that:

- Most of silx is MIT
- Modules using other licenses are accepted provided they do not impose anything to the end user. That means LGPL is accepted but GPL or BSD with citation clause are not.
- That if the end user is using PyQt4 or PyQt5, (s)he will be under GPL unless he owns a commercial license. The end user has the alternative of using PySide in order to be free since PySide is LGPL.
- That more details can be found in the copyright file.
