### ISSUE TITLE
StackView duplicates plot API

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#927]
With the refactoring of the plot axes (#909) and colormap (#913) it has become apparent that duplicating a subset of the plot API in StackView was a bad idea and is causing extra work. 

I suggest that we deprecate the duplicated API (`setGraphXLabel, resetZoom, getActiveImage, getGraphTitle,setGraphTitle,  isKeepDataAspectRatio, setKeepDataAspectRatio`...) to give us the option of removing the methods in a few releases,  and just provide a `getPlot()` method to replace them all.

The only drawback to this is that it will indirectly expose the entire plot API instead of just the useful subset of methods.

**Comment by vasole** [comment]
What is the drawback of those methods just calling self.getPlot().methopName?

**Comment by PiRK** [comment]
I believe it is preferable to be consistent throughout the project, so every time we change the "best practice" we need to fix all our internal code (e.g. https://github.com/silx-kit/silx/pull/909/files#diff-762cbffc2cee69b18c3551e1ee19bb85)

**Comment by vasole** [comment]
At no moment it was considered to get rid of those methods. They are there and that's it. A totally different thing is that we decided to use the object oriented API in our own code and temporarily marked those methods as deprecated.

**Comment by PiRK** [comment]
I understand this for PlotWidget, but StackView is a higher level widget that did not necessarily need to implement the same API initially. It was done because I thought that it did not cost much to do so (my usual mistake).

The other alternative was to inherit `PlotWidget`, which would completely remove the issue of maintaining the API. But the issue is that it would directly expose methods that should preferably not be called (`addImage`...).

**Comment by vasole** [comment]
My point of view is that it was done and not on last release.

Considering that the functional API is frozen it should not cost anything to maintain it. Concerning the StackView was our (your?) choice to modify those methods to follow the object oriented API but it was not necessary. If the functional API would have been kept calling the (already frozen) functional API no maintenance changes would have been necessary at the StackView level.

To suppress those methods is for me the equivalent of suppressing them from PlotWidget and that is something that is not going to be made. The functional API is simply frozen but not deprecated. People has been using it because:

- It is simpler to use interactively
- There was an OpenGL binding already implemented with that API.

**Comment by t20100** [comment]
To me the `getPlot` method is a good way for `StackView` to provide the `PlotWidget` API.

Even if the `PlotWidget` API is 'frozen', with time and needs, we will most probably add methods and arguments to existing methods, and proxies will have to keep up, + they duplicate the documentation.
