### ISSUE TITLE
[plot] ColorBar lacks support of RGB(A) image

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#969]
The ColorBar tries to compute a range from RGB(A) images when the colormap is in autoscale.
To reproduce:
```
from silx import sx
rgb = numpy.arange(4*4*3, dtype='uint8').reshape(4, 4, 3)
w = sx.imshow(rgb)
```
=> The colorbar displays a range of [0, 47].

**Comment by payno** [comment]
In fact the question following this is issue is how can we display colormap for rgb images ?

Because for now we should go from three-four informations (rgb-a) to one (colorbar scale).

After a discussion with @PiRK and @vallsv two solutions are possible for now.

First : display a blanck colormap with vmin=0 and vmax=255.
Second: divide the colormap on three-four channels rgb (a), always between 0 and 255

From my point of view I think the second option might be the better one.

**Comment by t20100** [comment]
For RGB images, the colorbar is meaningless.
Following further discussion with @PiRK and @vallsv, the proposed option would be to support `setColormap(None)` which would display an empty colormap without bounds (and eventually displays the Colorbar as a disabled widget).

**Comment by vasole** [comment]
I do not consider it meaningless if you have a colorbar per component.

**Comment by t20100** [comment]
Then it would be more 3 histograms or an intensity histogram rather than a colorbar, right?

**Comment by vasole** [comment]
It could be three colorbars associated to three different colormaps. If one uses an histogram to set them or not is different. Anyways, at we have a problem to fix and not an enhancement to be implemented.

BTW, we are going to need a slider to select a range within limits at a certain point.

**Comment by t20100** [comment]
Closing as ColorBar now handle it by being disabled
